# Funding options for rippled-zig
# Consider supporting the project through one of these platforms

# GitHub Sponsors
# github: [SMC17]

# Other platforms
# patreon: rippled-zig
# open_collective: rippled-zig
# ko_fi: rippled_zig

# Custom link
# custom: ["https://rippled-zig.org/donate"]

